plugins {
    id 'com.android.application'
}

android {
    namespace 'io.regime.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'io.regime.mobile'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0-phase1'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}
